const assert=require('node:assert/strict'),fs=require('node:fs'),H=require('../assets/history-engine'),{adapt}=require('../tools/import-canonical.cjs');const db=require('../data/canonical/v3.2.0/database.json'),seed=require('./fixtures/issue-001-history.json'),raw=adapt(db,seed),engine=H.createEngine(raw),q=engine.query();let n=0;function test(label,fn){fn();n++;console.log('PASS',label);}
test('canonical record counts and source identity retained',()=>{assert.equal(raw.weekly_scores.length,1168);assert.equal(raw.matchups.length,335);assert.equal(raw.championships.length,15);assert.equal(raw.franchises.length,16);assert.equal(db.seasonSummaries.length,48);assert.equal(db.seasonHonors.length,17);assert.equal(db.allTimeLedger.length,23);});
test('live production archive exactly matches validated canonical adaptation',()=>{assert.deepEqual(require('../data/history/archive.json'),raw);});
test('every imported week and matchup agrees with canonical source values',()=>{for(const s of db.weeklyScores)assert.equal(raw.weekly_scores.find(r=>r.season===s.season&&r.week===s.week&&r.franchise===s.franchiseId).score,s.points);for(const m of db.matchups){const g=raw.matchups.find(g=>g.season===m.season&&g.week===m.week&&[g.teamA,g.teamB].includes(m.teamId)&&[g.teamA,g.teamB].includes(m.opponentId));assert.ok(g);assert.equal(H.side(g,m.teamId).pf,m.teamPoints);assert.equal(H.side(g,m.teamId).pa,m.opponentPoints);}});
test('2026 seed and issue files are not overwritten by canonical adaptation',()=>{const sorted=a=>[...a].sort((x,y)=>x.id.localeCompare(y.id));assert.deepEqual(sorted(raw.weekly_scores.filter(s=>s.season===2026)),sorted(seed.weekly_scores));assert.deepEqual(sorted(raw.matchups.filter(g=>g.season===2026)),sorted(seed.matchups));assert.equal(engine.query('2026').scores.length,24);assert.equal(engine.query('2026').games.length,12);assert.equal(raw.seasons.find(s=>s.year===2026).status,'ytd');});
test('pre-2021 scoring has no fabricated opponents; H2H core covers only actual rows',()=>{for(let y=2016;y<=2020;y++){assert.equal(engine.query(String(y)).scores.length,112);assert.equal(engine.query(String(y)).games.length,0);}for(let y=2021;y<=2025;y++){const r=engine.query(String(y),'regular');assert.equal(r.games.length,y<2023?56:60);assert.equal(r.pairs.length>0,true);assert.equal(r.allplay.filter(r=>r.weeks).length,8);}});
test('MtFbWY is a separate legacy franchise and has its own scoring',()=>{assert.equal(engine.resolve('MtFbWY'),'may-the-forsett-be-with-you');assert.equal(engine.resolve('BSUAJ'),'big-ball-jam');assert.equal(engine.resolve('QotMA'),'big-ball-jam');assert.notEqual(engine.resolve('MtFbWY'),engine.resolve('Big Ball Jam'));assert.ok(q.career.find(c=>c.franchise==='may-the-forsett-be-with-you').games>0);});
test('Triple Crown requires all three matching verified honors and only 2021/2024 qualify',()=>{const crowns=raw.seasonHonors.filter(h=>h.tripleCrown===true&&h.regularSeasonChampionId===h.leagueChampionId&&h.leagueChampionId===h.pointsLeaderId);assert.deepEqual(crowns.map(h=>h.season),[2021,2024]);});
test('modern points and title honors reconcile; conflicting summary ranks remain review flags',()=>{for(const h of db.seasonHonors.filter(h=>h.status==='verified')){const standings=db.seasonSummaries.filter(s=>s.season===h.season);const first=standings.find(s=>s.regularSeasonRank===1);if(first&&first.franchiseId!==h.regularSeasonChampionId){assert.ok(raw.discrepancies.some(d=>d.includes(String(h.season)+' summary rank')));assert.ok(raw.seasons.find(s=>s.year===h.season).standings.every(s=>s.lastPlace===null));}const scores=engine.query(String(h.season),'regular').seasonRows;assert.equal([...scores].sort((a,b)=>b.pf-a.pf)[0].franchise,h.pointsLeaderId);assert.equal(db.championships.find(c=>c.season===h.season).championId,h.leagueChampionId);}});
test('explicit unknowns are preserved, no 2010 or 2026 champion',()=>{const honors=y=>raw.seasonHonors.find(h=>h.season===y);assert.equal(honors(2010).leagueChampionId,null);assert.equal(honors(2011).regularSeasonChampionId,null);assert.equal(honors(2020).pointsLeaderId,null);assert.equal(honors(2026).leagueChampionId,null);assert.equal(raw.championships.some(c=>c.season===2010||c.season===2026),false);});
test('v3.2 canonical 2020 corrections and reviewed ledger quarantine',()=>{assert.equal(raw.championships.find(c=>c.season===2020).champion,'logjammin');assert.equal(raw.seasonHonors.find(h=>h.season===2020).regularSeasonChampionId,'logjammin');assert.equal(q.career.find(c=>c.franchise==='big-ball-jam').titles,4);assert.equal(q.career.find(c=>c.franchise==='logjammin').titles,2);assert.ok(raw.discrepancies.some(d=>d.includes('QofMA')));assert.ok(raw.discrepancies.some(d=>d.includes('May the Forsett')));});
test('postseason scores remain separate from regular season and known finals reconcile',()=>{assert.equal(raw.matchups.filter(g=>g.gameType!=='regular').length,31);assert.equal(raw.matchups.filter(g=>g.gameType==='championship').length,5);assert.equal(q.playoffRows.some(r=>r.eliminators.length),true);for(const c of raw.championships.filter(c=>c.matchupId)){const g=raw.matchups.find(g=>g.id===c.matchupId);assert.equal(H.side(g,c.champion).pf,c.championScore);assert.equal(H.side(g,c.runnerUp).pf,c.runnerUpScore);}assert.equal(engine.query('all','regular').games.length,304);});
test('historical sections have evidence-backed content',()=>{for(const k of ['pairs','lopsided','even','changes','revenge','curses','volatility','stretches','seasonRows','champs'])assert.ok(q[k].length>0,k);for(const pair of q.pairs){const reverse=engine.rivalry(q,pair.opponent,pair.franchise);assert.equal(pair.wins,reverse.losses);assert.equal(pair.losses,reverse.wins);assert.equal(pair.pf,reverse.pa);}});
test('canonical archive imported without source-document instruction execution',()=>{for(const f of ['database.json','franchises.json','weekly-scores.json','matchups.json','championships.json','season-honors.json','definitions.json','unresolved.json']){const sha=require('../data/canonical/v3.2.0/SHA256.json')[f];assert.equal(require('node:crypto').createHash('sha256').update(fs.readFileSync('data/canonical/v3.2.0/'+f)).digest('hex'),sha);}assert.equal(fs.existsSync('data/canonical/v3.2.0/CODEX_IMPORT_INSTRUCTIONS.txt'),false);});
console.log(n+' canonical tests passed.');
