const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..'),issues=JSON.parse(fs.readFileSync(path.join(root,'data/issues.json')));
const near=(a,b,msg,tol=.015)=>assert(Math.abs(a-b)<=tol,`${msg}: ${a} vs ${b}`);
for(const issue of issues){const d=JSON.parse(fs.readFileSync(path.join(root,`issues/${issue.id}/data.json`)));assert.equal(d.teams.length,8);assert.equal(new Set(d.teams.map(t=>t.id)).size,8);assert.equal(d.games.length,d.through_week*4);assert.equal(new Set(d.teams.map(t=>t.rank)).size,8);
 for(const t of d.teams){let gs=d.games.filter(g=>g.a===t.id||g.b===t.id);assert.equal(gs.length,d.through_week);assert.equal(new Set(gs.map(g=>g.week)).size,d.through_week);assert.equal(gs.filter(g=>g.a===t.id).length,t.wins);assert.equal(gs.filter(g=>g.b===t.id).length,t.losses);near(gs.reduce((s,g)=>s+(g.a===t.id?g.a_score:g.b_score),0),t.pf,t.name+' PF');near(gs.reduce((s,g)=>s+(g.a===t.id?g.b_score:g.a_score),0),t.pa,t.name+' PA');near(t.pf/d.through_week,t.average_pf,t.name+' average PF');near(t.pa/d.through_week,t.average_pa,t.name+' average PA');near(t.pf/t.optimum*100,t.source_efficiency,t.name+' efficiency');assert(t.optimum>=t.pf);assert.equal(Object.keys(t.positions).length,9);}
 for(const g of d.games){assert(g.a_score>g.b_score);assert(d.teams.some(t=>t.id===g.a));assert(d.teams.some(t=>t.id===g.b));}
 assert.equal(new Set(d.projections.flatMap(p=>[p.a,p.b])).size,8);
 for(const p of d.draft.picks){if(p.uncertain)continue;assert(p.round>=1&&p.round<=26);assert(p.pick_in_round>=1&&p.pick_in_round<=8);if(p.overall_pick!=null)assert.equal(p.overall_pick,(p.round-1)*8+p.pick_in_round);}
 const delta=d.teams.map(t=>({team:t.short,unallocated:+(t.pf-Object.values(t.positions).reduce((a,b)=>a+b,0)).toFixed(2)}));console.log('PASS issue '+d.issue+': source totals, records, averages, efficiency, all teams, projections, draft slots');console.log('Source positional differences (displayed as supplied):',delta);
}
for(const p of ['index.html','issues/001/index.html','archive/index.html']){const html=fs.readFileSync(path.join(root,p),'utf8');for(const match of html.matchAll(/(?:href|src)="([^"]+)"/g)){let u=match[1].split('#')[0];if(!u||u.startsWith('#')||u.startsWith('data:'))continue;assert(!u.startsWith('/'),'Absolute path would break project Pages');let dest=path.resolve(path.dirname(path.join(root,p)),u);assert(fs.existsSync(dest),'Missing linked file '+dest);}assert(html.includes('data-base='));}
const js=fs.readFileSync(path.join(root,'assets/app.js'),'utf8');new Function(js);assert(js.includes('t.pf/t.optimum*100'));assert(js.includes('t.optimum-t.pf'));assert(!js.includes('681.68'),'Charts must read JSON, not duplicate source values');console.log('PASS static routes, relative assets, shared JSON chart source and JavaScript syntax');

